import 'package:client/data/models/category.dart';
import 'package:client/data/models/product.dart';

class InventoryMockData {
  InventoryMockData._();

  static const categories = [
    Category(id: 1, name: 'Cement', description: 'Cement and masonry binders.'),
    Category(
      id: 2,
      name: 'Plumbing',
      description: 'Pipes, fittings, and fixtures.',
    ),
    Category(
      id: 3,
      name: 'Electrical',
      description: 'Wiring and electrical devices.',
    ),
    Category(
      id: 4,
      name: 'Lumber',
      description: 'Plywood and timber products.',
    ),
    Category(
      id: 5,
      name: 'Steel',
      description: 'Reinforcing and structural steel.',
    ),
    Category(
      id: 6,
      name: 'Roofing',
      description: 'Roof sheets and accessories.',
    ),
    Category(
      id: 7,
      name: 'Hand Tools',
      description: 'Manual construction tools.',
    ),
    Category(
      id: 8,
      name: 'Fasteners',
      description: 'Nails, screws, and anchors.',
    ),
  ];

  static const products = [
    Product(
      id: 1,
      categoryId: 1,
      categoryName: 'Cement',
      brandId: 1,
      brandName: 'Holcim',
      baseName: 'Portland Cement',
      description: 'General-purpose Portland cement.',
      imageUrl: '',
      isActive: true,
      variants: [
        ProductVariant(
          id: 1,
          variantName: '40 kg Bag',
          baseUomCode: 'Bag',
          isActive: true,
          sku: 'CEM-HOL-40',
          qrIdentifier: 'MAT-00001',
          costPrice: 235,
          sellingPrice: 270,
          currentStock: 130,
          reorderLevel: 30,
          storageLocation: 'Rack A-01',
        ),
      ],
    ),
    Product(
      id: 2,
      categoryId: 1,
      categoryName: 'Cement',
      brandId: 2,
      brandName: 'Republic',
      baseName: 'Masonry Cement',
      description: 'Cement for plastering and masonry.',
      imageUrl: '',
      isActive: true,
      variants: [
        ProductVariant(
          id: 2,
          variantName: '40 kg Bag',
          baseUomCode: 'Bag',
          isActive: true,
          sku: 'CEM-REP-40',
          qrIdentifier: 'MAT-00002',
          costPrice: 215,
          sellingPrice: 250,
          currentStock: 24,
          reorderLevel: 25,
          storageLocation: 'Rack A-02',
        ),
      ],
    ),
    Product(
      id: 3,
      categoryId: 2,
      categoryName: 'Plumbing',
      brandId: 3,
      brandName: 'Neltex',
      baseName: 'PVC Pipe',
      description: 'PVC pipe for water-line installations.',
      imageUrl: '',
      isActive: true,
      variants: [
        ProductVariant(
          id: 3,
          variantName: '1/2 inch × 3 m',
          baseUomCode: 'Piece',
          isActive: true,
          sku: 'PVC-NEL-050',
          qrIdentifier: 'MAT-00021',
          costPrice: 135,
          sellingPrice: 180,
          currentStock: 42,
          reorderLevel: 15,
          storageLocation: 'Rack B-02',
        ),
        ProductVariant(
          id: 4,
          variantName: '3/4 inch × 3 m',
          baseUomCode: 'Piece',
          isActive: true,
          sku: 'PVC-NEL-075',
          qrIdentifier: 'MAT-00022',
          costPrice: 175,
          sellingPrice: 225,
          currentStock: 19,
          reorderLevel: 15,
          storageLocation: 'Rack B-02',
        ),
        ProductVariant(
          id: 5,
          variantName: '1 inch × 3 m',
          baseUomCode: 'Piece',
          isActive: true,
          sku: 'PVC-NEL-100',
          qrIdentifier: 'MAT-00023',
          costPrice: 230,
          sellingPrice: 290,
          currentStock: 8,
          reorderLevel: 15,
          storageLocation: 'Rack B-03',
        ),
      ],
    ),
    Product(
      id: 4,
      categoryId: 2,
      categoryName: 'Plumbing',
      brandId: 3,
      brandName: 'Neltex',
      baseName: 'PVC Elbow',
      description: 'Pressure-rated PVC elbow fitting.',
      imageUrl: '',
      isActive: true,
      variants: [
        ProductVariant(
          id: 6,
          variantName: '1/2 inch',
          baseUomCode: 'Piece',
          isActive: true,
          sku: 'ELB-NEL-050',
          qrIdentifier: 'MAT-00024',
          costPrice: 18,
          sellingPrice: 28,
          currentStock: 65,
          reorderLevel: 20,
          storageLocation: 'Bin B-10',
        ),
        ProductVariant(
          id: 7,
          variantName: '1 inch',
          baseUomCode: 'Piece',
          isActive: true,
          sku: 'ELB-NEL-100',
          qrIdentifier: 'MAT-00025',
          costPrice: 32,
          sellingPrice: 48,
          currentStock: 12,
          reorderLevel: 15,
          storageLocation: 'Bin B-11',
        ),
      ],
    ),
    Product(
      id: 5,
      categoryId: 2,
      categoryName: 'Plumbing',
      brandId: 4,
      brandName: 'HCG',
      baseName: 'Faucet',
      description: 'Chrome utility faucet.',
      imageUrl: '',
      isActive: true,
      variants: [
        ProductVariant(
          id: 8,
          variantName: 'Standard 1/2 inch',
          baseUomCode: 'Piece',
          isActive: true,
          sku: 'FAU-HCG-050',
          qrIdentifier: 'MAT-00026',
          costPrice: 290,
          sellingPrice: 390,
          currentStock: 14,
          reorderLevel: 8,
          storageLocation: 'Shelf B-05',
        ),
      ],
    ),
    Product(
      id: 6,
      categoryId: 4,
      categoryName: 'Lumber',
      brandId: 5,
      brandName: 'Queen Builders',
      baseName: 'Marine Plywood',
      description: 'Moisture-resistant plywood sheet.',
      imageUrl: '',
      isActive: true,
      variants: [
        ProductVariant(
          id: 9,
          variantName: '1/2 inch × 4 ft × 8 ft',
          baseUomCode: 'Sheet',
          isActive: true,
          sku: 'PLY-MAR-050',
          qrIdentifier: 'MAT-00031',
          costPrice: 890,
          sellingPrice: 1050,
          currentStock: 18,
          reorderLevel: 10,
          storageLocation: 'Rack C-01',
        ),
        ProductVariant(
          id: 10,
          variantName: '3/4 inch × 4 ft × 8 ft',
          baseUomCode: 'Sheet',
          isActive: true,
          sku: 'PLY-MAR-075',
          qrIdentifier: 'MAT-00032',
          costPrice: 1250,
          sellingPrice: 1450,
          currentStock: 0,
          reorderLevel: 10,
          storageLocation: 'Rack C-02',
        ),
      ],
    ),
    Product(
      id: 7,
      categoryId: 3,
      categoryName: 'Electrical',
      brandId: 6,
      brandName: 'Royu',
      baseName: 'Convenience Outlet',
      description: 'Duplex convenience outlet.',
      imageUrl: '',
      isActive: true,
      variants: [
        ProductVariant(
          id: 11,
          variantName: 'Universal Duplex',
          baseUomCode: 'Piece',
          isActive: true,
          sku: 'OUT-ROY-UNI',
          qrIdentifier: 'MAT-00041',
          costPrice: 95,
          sellingPrice: 135,
          currentStock: 36,
          reorderLevel: 12,
          storageLocation: 'Shelf D-03',
        ),
      ],
    ),
    Product(
      id: 8,
      categoryId: 3,
      categoryName: 'Electrical',
      brandId: 7,
      brandName: 'Phelps Dodge',
      baseName: 'Electrical Wire',
      description: 'Copper building wire.',
      imageUrl: '',
      isActive: true,
      variants: [
        ProductVariant(
          id: 12,
          variantName: '2.0 mm² × 150 m',
          baseUomCode: 'Roll',
          isActive: true,
          sku: 'WIR-PD-200',
          qrIdentifier: 'MAT-00042',
          costPrice: 2150,
          sellingPrice: 2490,
          currentStock: 7,
          reorderLevel: 5,
          storageLocation: 'Rack D-05',
        ),
        ProductVariant(
          id: 13,
          variantName: '3.5 mm² × 150 m',
          baseUomCode: 'Roll',
          isActive: true,
          sku: 'WIR-PD-350',
          qrIdentifier: 'MAT-00043',
          costPrice: 3400,
          sellingPrice: 3890,
          currentStock: 4,
          reorderLevel: 5,
          storageLocation: 'Rack D-06',
        ),
      ],
    ),
    Product(
      id: 9,
      categoryId: 5,
      categoryName: 'Steel',
      brandId: 8,
      brandName: 'SteelAsia',
      baseName: 'Deformed Steel Bar',
      description: 'Grade 40 reinforcing steel bar.',
      imageUrl: '',
      isActive: true,
      variants: [
        ProductVariant(
          id: 14,
          variantName: '10 mm × 6 m',
          baseUomCode: 'Piece',
          isActive: true,
          sku: 'BAR-SA-10',
          qrIdentifier: 'MAT-00051',
          costPrice: 155,
          sellingPrice: 185,
          currentStock: 95,
          reorderLevel: 30,
          storageLocation: 'Yard E-01',
        ),
        ProductVariant(
          id: 15,
          variantName: '12 mm × 6 m',
          baseUomCode: 'Piece',
          isActive: true,
          sku: 'BAR-SA-12',
          qrIdentifier: 'MAT-00052',
          costPrice: 220,
          sellingPrice: 260,
          currentStock: 28,
          reorderLevel: 30,
          storageLocation: 'Yard E-02',
        ),
      ],
    ),
    Product(
      id: 10,
      categoryId: 6,
      categoryName: 'Roofing',
      brandId: 9,
      brandName: 'Union Galvasteel',
      baseName: 'Corrugated Roofing Sheet',
      description: 'Pre-painted corrugated roofing.',
      imageUrl: '',
      isActive: true,
      variants: [
        ProductVariant(
          id: 16,
          variantName: '0.4 mm × 8 ft',
          baseUomCode: 'Sheet',
          isActive: true,
          sku: 'ROOF-UG-08',
          qrIdentifier: 'MAT-00061',
          costPrice: 520,
          sellingPrice: 620,
          currentStock: 22,
          reorderLevel: 12,
          storageLocation: 'Rack F-01',
        ),
        ProductVariant(
          id: 17,
          variantName: '0.4 mm × 10 ft',
          baseUomCode: 'Sheet',
          isActive: true,
          sku: 'ROOF-UG-10',
          qrIdentifier: 'MAT-00062',
          costPrice: 650,
          sellingPrice: 765,
          currentStock: 9,
          reorderLevel: 12,
          storageLocation: 'Rack F-02',
        ),
      ],
    ),
    Product(
      id: 11,
      categoryId: 7,
      categoryName: 'Hand Tools',
      brandId: 10,
      brandName: 'Stanley',
      baseName: 'Claw Hammer',
      description: 'Fiberglass-handle claw hammer.',
      imageUrl: '',
      isActive: true,
      variants: [
        ProductVariant(
          id: 18,
          variantName: '16 oz',
          baseUomCode: 'Piece',
          isActive: true,
          sku: 'HAM-STA-16',
          qrIdentifier: 'MAT-00071',
          costPrice: 420,
          sellingPrice: 525,
          currentStock: 16,
          reorderLevel: 6,
          storageLocation: 'Shelf G-02',
        ),
      ],
    ),
    Product(
      id: 12,
      categoryId: 8,
      categoryName: 'Fasteners',
      brandId: 5,
      brandName: 'Queen Builders',
      baseName: 'Common Nail',
      description: 'General construction common nail.',
      imageUrl: '',
      isActive: true,
      variants: [
        ProductVariant(
          id: 19,
          variantName: '2 inch × 1 kg',
          baseUomCode: 'Box',
          isActive: true,
          sku: 'NAIL-COM-02',
          qrIdentifier: 'MAT-00081',
          costPrice: 72,
          sellingPrice: 95,
          currentStock: 48,
          reorderLevel: 15,
          storageLocation: 'Bin H-01',
        ),
        ProductVariant(
          id: 20,
          variantName: '4 inch × 1 kg',
          baseUomCode: 'Box',
          isActive: true,
          sku: 'NAIL-COM-04',
          qrIdentifier: 'MAT-00082',
          costPrice: 78,
          sellingPrice: 105,
          currentStock: 0,
          reorderLevel: 12,
          storageLocation: 'Bin H-02',
        ),
      ],
    ),
  ];
}
