services:
  db:
    image: postgres:15-alpine
    container_name: buildpro_db
    environment:
      POSTGRES_DB: buildpro_pos
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    ports:
      - "5433:5432" # Maps Docker's 5432 to your PC's 5433 to avoid conflicts!
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend_django
    container_name: config
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend_django:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data: