# Generated by Django 5.2.17 on 2026-08-22 15:03

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_supplier_alter_variantuom_conversion_factor_and_more'),
        ('pos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(help_text='The contractor / construction firm for this project.', limit_choices_to={'customer_type__in': ['CONTRACTOR', 'CONSTRUCTION_FIRM']}, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='pos.customer')),
            ],
            options={
                'db_table': 'requisitions_project',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PARTIAL', 'Partially Released'), ('RELEASED', 'Fully Released'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=12)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Manager who approved the request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisitions', to='requisitions.project')),
                ('requested_by', models.ForeignKey(help_text='Site foreman who requested the materials.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'requisitions_req',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('is_used', models.BooleanField(db_index=True, default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('requisition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token', to='requisitions.requisition')),
            ],
            options={
                'db_table': 'requisitions_token',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequisitionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('released_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='requisitions.requisition')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisition_items', to='inventory.productvariant')),
            ],
            options={
                'db_table': 'requisitions_item',
            },
        ),
        migrations.AddIndex(
            model_name='requisition',
            index=models.Index(fields=['project', '-created_at'], name='requisition_project_b2eae9_idx'),
        ),
        migrations.AddIndex(
            model_name='requisition',
            index=models.Index(fields=['status'], name='requisition_status_ac0497_idx'),
        ),
    ]
