# Generated by Django 5.2.17 on 2026-08-22 10:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_supplier_alter_variantuom_conversion_factor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('customer_type', models.CharField(choices=[('WALK_IN', 'Walk-in'), ('REGULAR', 'Regular'), ('CONTRACTOR', 'Contractor'), ('CONSTRUCTION_FIRM', 'Construction Firm')], default='WALK_IN', max_length=20)),
                ('contact_details', models.CharField(blank=True, default='', max_length=255)),
                ('tin_no', models.CharField(blank=True, default='', max_length=50)),
                ('total_credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pos_customer',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SalesTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_no', models.CharField(db_index=True, max_length=50, unique=True)),
                ('trans_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('vatable_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('source', models.CharField(choices=[('WALK_IN', 'Walk-in'), ('REQUISITION', 'Requisition')], default='WALK_IN', max_length=15)),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('VOID', 'Void'), ('REFUNDED', 'Refunded')], default='COMPLETED', max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_transactions', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='pos.customer')),
            ],
            options={
                'db_table': 'pos_transaction',
                'ordering': ['-trans_date'],
            },
        ),
        migrations.CreateModel(
            name='SalesItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('variant_uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_items', to='inventory.variantuom')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.salestransaction')),
            ],
            options={
                'db_table': 'pos_sales_item',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('GCASH', 'GCash'), ('BANK_TRANSFER', 'Bank Transfer')], default='CASH', max_length=15)),
                ('amount_tendered', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference_no', models.CharField(blank=True, default='', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='pos.salestransaction')),
            ],
            options={
                'db_table': 'pos_payment',
            },
        ),
        migrations.CreateModel(
            name='OfficialReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('or_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('terminal_no', models.CharField(default='POS-01', max_length=20)),
                ('printed_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receipt', to='pos.salestransaction')),
            ],
            options={
                'db_table': 'pos_receipt',
                'ordering': ['-printed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='salestransaction',
            index=models.Index(fields=['-trans_date'], name='pos_transac_trans_d_48d53c_idx'),
        ),
        migrations.AddIndex(
            model_name='salestransaction',
            index=models.Index(fields=['status'], name='pos_transac_status_a6335c_idx'),
        ),
    ]
