# Generated by Django 5.2.17 on 2026-08-22 10:32

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectibleLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('balance_due', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('PARTIAL', 'Partial'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue')], db_index=True, default='OPEN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collectible_ledgers', to='pos.customer')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collectible_ledgers', to='pos.salestransaction')),
            ],
            options={
                'verbose_name': 'collectible ledger',
                'verbose_name_plural': 'collectible ledgers',
                'db_table': 'collectibles_ledger',
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='CollectiblePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_method', models.CharField(max_length=50)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('official_receipt_no', models.CharField(blank=True, default='', max_length=100)),
                ('collectible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='collectibles.collectibleledger')),
                ('processed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'collectible payment',
                'verbose_name_plural': 'collectible payments',
                'db_table': 'collectibles_payment',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.AddIndex(
            model_name='collectibleledger',
            index=models.Index(fields=['status'], name='collectible_status_8c9836_idx'),
        ),
        migrations.AddIndex(
            model_name='collectibleledger',
            index=models.Index(fields=['customer'], name='collectible_custome_590cf0_idx'),
        ),
        migrations.AddIndex(
            model_name='collectibleledger',
            index=models.Index(fields=['customer', 'status'], name='collectible_custome_6c7453_idx'),
        ),
        migrations.AddIndex(
            model_name='collectiblepayment',
            index=models.Index(fields=['collectible', '-payment_date'], name='collectible_collect_c9dcaa_idx'),
        ),
    ]
